### ISSUE TITLE
Portal 报错 Internal Server Error

### ISSUE THREAD

**Issue by diegozhu** [open-falcon/portal#14]
Python 2.6.6
CentOS 6.5
go version go1.5 linux/amd64

portal http port : 8867

start up as root , and portal is  /usr/local/go/src/open-falcon/Portal
below is error message:

**Comment by diegozhu** [comment]
[2016-04-19 17:20:35 +0000] [31404] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/local/go/src/github.com/open-falcon/Portal/web/**init**.py", line 50, in before_request
    return redirect_to_sso()
  File "/usr/local/go/src/github.com/open-falcon/Portal/web/**init**.py", line 58, in redirect_to_sso
    resp = make_response(redirect(uic.login_url(sig, urllib.quote(request.url))))
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/werkzeug/utils.py", line 364, in redirect
    response.headers['Location'] = location
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/werkzeug/datastructures.py", line 1167, in **setitem**
    self.set(key, value)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/werkzeug/datastructures.py", line 1126, in set
    self._validate_value(_value)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/werkzeug/datastructures.py", line 1093, in _validate_value
    raise ValueError('Detected newline in header value.  This is '
ValueError: Detected newline in header value.  This is a potential security problem

==> var/access.log <==
10.10.10.32 - - [19/Apr/2016:17:20:35 +0800] "GET / HTTP/1.1" 500 - "-" "-"

==> var/app.log <==
[2016-04-19 17:20:35 +0000] [31414] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/local/go/src/github.com/open-falcon/Portal/web/**init**.py", line 50, in before_request
    return redirect_to_sso()
  File "/usr/local/go/src/github.com/open-falcon/Portal/web/**init**.py", line 58, in redirect_to_sso
    resp = make_response(redirect(uic.login_url(sig, urllib.quote(request.url))))
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/werkzeug/utils.py", line 364, in redirect
    response.headers['Location'] = location
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/werkzeug/datastructures.py", line 1167, in **setitem**
    self.set(key, value)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/werkzeug/datastructures.py", line 1126, in set
    self._validate_value(_value)
  File "/usr/local/go/src/github.com/open-falcon/Portal/env/lib/python2.6/site-packages/werkzeug/datastructures.py", line 1093, in _validate_value
    raise ValueError('Detected newline in header value.  This is '
ValueError: Detected newline in header value.  This is a potential security problem

==> var/access.log <==
10.10.10.32 - - [19/Apr/2016:17:20:35 +0800] "GET /favicon.ico HTTP/1.1" 500 - "-" "-"

**Comment by diegozhu** [comment]
any help will be appreciated.

**Comment by diegozhu** [comment]
fixed.
frame/config.py
UIC_ADDRESS was wrongly configured.
But anyway , I think we should notice user better message. UX . So I'll left this issue open.

**Comment by wenchao0809** [comment]
I have the same question, can you tell me how edit config.py? I am not understand this document about portal.[https://book.open-falcon.org/zh/quick_install/judge_components.html](url) @diegozhu @laiwei

**Comment by luampm** [comment]
potal/frame/config.py 里面的地址配置要与 fe/cfg.json 配置相匹配:
 仅供参考 (我的是这样解决的 )
potal/frame/config.py 
 UIC_ADDRESS = {
     'internal': 'http://127.0.0.1:1234',
     'external': 'http://192.168.0.237:1234',
 }
 
 fe/cfg.json 
 "http": {
         "enabled": true,
         "listen": "0.0.0.0:1234"
      },
