### ISSUE TITLE
Portal报错。

### ISSUE THREAD

**Issue by dadait** [open-falcon/portal#23]
==> var/app.log <==
[2016-08-22 14:45:49 +0000] [5177] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/home/work/open-falcon/portal/web/**init**.py", line 46, in before_request
    return redirect_to_sso()
  File "/home/work/open-falcon/portal/web/**init**.py", line 57, in redirect_to_sso
    sig = uic.gen_sig()
  File "/home/work/open-falcon/portal/frame/api/uic.py", line 11, in gen_sig
    return requests.get(url).content
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/api.py", line 55, in get
    return request('get', url, *_kwargs)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, *_kwargs)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /sso/sig (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

==> var/access.log <==
124.205.181.226 - - [22/Aug/2016:14:45:49 +0800] "GET / HTTP/1.1" 500 - "-" "-"

==> var/app.log <==
[2016-08-22 14:45:50 +0000] [5173] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/home/work/open-falcon/portal/web/**init**.py", line 46, in before_request
    return redirect_to_sso()
  File "/home/work/open-falcon/portal/web/**init**.py", line 57, in redirect_to_sso
    sig = uic.gen_sig()
  File "/home/work/open-falcon/portal/frame/api/uic.py", line 11, in gen_sig
    return requests.get(url).content
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/api.py", line 55, in get
    return request('get', url, *_kwargs)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, *_kwargs)
  File "/home/work/open-falcon/portal/env/lib/python2.6/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /sso/sig (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

**Comment by dadait** [comment]
已解决
portal的frame/config.py中的默认配置UIC_ADDRESS端口都是8080.我只改了IP地址，没改端口。
而fe的默认配置是端口是1234
大意导致的。
